{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "giropopssenhas.fullname" . }}
  labels:
    {{- include "giropopssenhas.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName:
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "giropopssenhas.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{ end }}