apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-service
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-redis
  type: {{ .Values.redis.service.type }}