apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: {{ .Chart.Name }}-redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: 6379
          name: redis
        replicas: "{{ .Values.redis.replicas }}"
        resources:
          requests:
            cpu: "{{ .Values.redis.resources.requests.cpu }}"
            memory: "{{ .Values.redis.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.redis.resources.limits.cpu }}"
            memory: "{{ .Values.redis.resources.limits.memory }}"